Android.mk: workaround missing-field-initializers error
Without -Wno-missing-field-initializers, GCC 4.9 generates below
errors, so add it to Android.mk. While we're at it, also add
-Wno-format-zero-length to sync with host/xtest/Makefile.

external/optee_test/host/xtest/regression_5000.c:485:40: error: missing field 'session' initializer [-Werror,-Wmissing-field-initializers]
        struct xtest_session connection = { c };
                                              ^

external/optee_test/host/xtest/regression_2000.c:46:22: error: missing field 'paramTypes' initializer [-Werror,-Wmissing-field-initializers]
        TEEC_Operation op = TEEC_OPERATION_INITIALIZER;
                            ^
external/optee_test/host/xtest/xtest_helpers.h:43:40: note: expanded from macro 'TEEC_OPERATION_INITIALIZER'
                                       ^

external/optee_test/host/xtest/regression_2000.c:272:29: error: missing field 'session_id' initializer [-Werror,-Wmissing-field-initializers]
        TEEC_Session session = { 0 };
                                   ^

Signed-off-by: Victor Chong <victor.chong@linaro.org>
Acked-by: Jerome Forissier <jerome.forissier@linaro.org>